[package]
name = "pluxer-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
pluxer-backend.workspace = true
pluxer-database.workspace = true
tokio = { workspace = true, features = ["macros"] }
dotenv.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
serde_json = "1.0.151"
anyhow = "1.0.104"
ulid.workspace = true
pawkit-logger = "0.1.25"
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
csscolorparser = "0.8.4"
base64 = "0.23.1"
moka = { version = "0.12.16", features = ["future"] }
reqwest = { version = "0.12.28", features = ["multipart"] }

[features]
default = ["fluxer"]
fluxer = ["pluxer-backend/fluxer"]
