[workspace]
resolver = "3"

members = ["backend",
    "database"
, "frontend/fluxer"]

[workspace.dependencies]
pluxer-database.path = "./database"
pluxer-backend.path = "./backend"

ulid = "3.0.0"

sea-orm = { version = "2.0.2", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }

tokio = { version = "1", features = ["full"] }
