[package]
name = "pluxer-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
fluxer-builders.optional = true

fluxer-builders.workspace = true
fluxer-core.optional = true

fluxer-core.workspace = true
fluxer-rest.optional = true

fluxer-rest.workspace = true
fluxer-types.optional = true

fluxer-types.workspace = true
fluxer-util.optional = true

fluxer-util.workspace = true
fluxer-ws.optional = true

fluxer-ws.workspace = true
pluxer-database.workspace = true
reqwest = { version = "0.12.28", features = ["multipart"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[features]
default = ["fluxer"]

fluxer = ["fluxer-builders", "fluxer-core", "fluxer-rest", "fluxer-types", "fluxer-util", "fluxer-ws"]
